steps:
  - id: Configure git
    name: "gcr.io/cloud-builders/git"
    secretEnv: ["SSH_KEY"]
    entrypoint: "bash"
    args:
      - -c
      - |
        git config --global init.defaultBranch main
        git config --global user.email "gavin@gavinminami.com"
        git config --global user.name "Gavin Minami"
        mkdir /root/.ssh
        echo "$$SSH_KEY" >> /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        cp known_hosts.github /root/.ssh/known_hosts
        ls -al /root/.ssh
    volumes:
      - name: "home"
        path: /root/

  - id: Git clone
    name: "gcr.io/cloud-builders/git"
    args:
      - clone
      - --recurse-submodules
      - git@github.com:gavindotio/nanostack-sdk
    volumes:
      - name: "home"
        path: /root/

  - id: Decrypt .npmrc
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - kms
      - decrypt
      - --ciphertext-file=npmrc.enc
      - --plaintext-file=/root/.npmrc
      - --location=global
      - --keyring=build
      - --key=npm-key
    volumes:
      - name: "home"
        path: /root/

  - id: Install dependencies
    name: "node"
    dir: "/workspace/nanostack-sdk"
    entrypoint: "npm"
    args: ["ci"]

  - id: Increment version and tag release
    name: "node"
    dir: "/workspace/nanostack-sdk"
    entrypoint: "npm"
    args: ["run", "release"]

  - id: Push tag to git
    name: "gcr.io/cloud-builders/git"
    dir: "/workspace/nanostack-sdk"
    args:
      - push
      - --follow-tags
      - origin
      - main
    volumes:
      - name: "home"
        path: /root/

  - id: Publish NPM module
    name: "node"
    dir: "/workspace/nanostack-sdk"
    entrypoint: "npm"
    args: ["publish"]
    env:
      - HOME=/root/
    volumes:
      - name: "home"
        path: /root/

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github-ci/versions/latest
      env: "SSH_KEY"
