steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - kms
      - decrypt
      - --ciphertext-file=npmrc.enc
      - --plaintext-file=/root/.npmrc
      - --location=global
      - --keyring=build
      - --key=npm-key
    volumes:
      - name: "home"
        path: /root/

  - name: "node"
    entrypoint: "npm"
    args: ["install"]

  - name: "node"
    entrypoint: "npm"
    args: ["run", "release"]

  - name: "gcr.io/cloud-builders/npm"
    args: ["publish"]
    env:
      - HOME=/root/
    volumes:
      - name: "home"
        path: /root/
