steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - kms
      - decrypt
      - --ciphertext-file=npmrc.enc
      - --plaintext-file=/root/.npmrc
      - --location=global
      - --keyring=build
      - --key=npm-key
    volumes:
      - name: "home"
        path: /root/

  - name: "node"
    entrypoint: "npm"
    args: ["ci"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        git config --global user.email "gavin@gavinminami.com"
        git config --global user.name "Gavin Minami"

  - name: "node"
    entrypoint: "npm"
    args: ["run", "release"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        ls -al
        git push --follow-tags origin main

  - name: "node"
    entrypoint: "npm"
    args: ["publish"]
    env:
      - HOME=/root/
    volumes:
      - name: "home"
        path: /root/
