steps:
  - name: "gcr.io/cloud-builders/git"
    secretEnv: ["SSH_KEY"]
    entrypoint: "bash"
    args:
      - -c
      - |
        git config --global init.defaultBranch main
        mkdir /root/.ssh
        echo "$$SSH_KEY" >> /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        cp known_hosts.github /root/.ssh/known_hosts
    volumes:
      - name: "home"
        path: /root/

  # Clone the repository
  - name: "gcr.io/cloud-builders/git"
    args:
      - clone
      - --recurse-submodules
      - git@github.com:gavindotio/nanostack-sdk
    volumes:
      - name: "home"
        path: /root/

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - kms
      - decrypt
      - --ciphertext-file=npmrc.enc
      - --plaintext-file=/root/.npmrc
      - --location=global
      - --keyring=build
      - --key=npm-key
    volumes:
      - name: "home"
        path: /root/

  - name: "node"
    entrypoint: "npm"
    args: ["ci"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        git config --global user.email "gavin@gavinminami.com"
        git config --global user.name "Gavin Minami"

  - name: "node"
    entrypoint: "npm"
    args: ["run", "release"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        ls -al
        git push --follow-tags origin main

  - name: "node"
    entrypoint: "npm"
    args: ["publish"]
    env:
      - HOME=/root/
    volumes:
      - name: "home"
        path: /root/

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github-ci/versions/latest
      env: "SSH_KEY"
